# Generated by Django 5.0.6 on 2024-07-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Location', models.TextField()),
                ('Breed', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
