# Generated by Django 5.0.6 on 2024-07-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.TextField(default='Available'),
        ),
    ]
